#!/usr/bin/env python3

import argparse
import compression.zstd
import hashlib
import pathlib
import shutil
import struct
import subprocess
import sys

parser = argparse.ArgumentParser(
  prog='mrvcpack', description='Wrap contract ELF files in an MRVC envelope')

parser.add_argument('-n', '--dry-run', action='store_true',
  help='Print the commands that would run, without running them')

parser.add_argument('-u', '--uncompressed', action='store_true',
  help='Do not zstd-compress the code payload')

parser.add_argument('-v', '--verbose', action='count', default=0,
  help='Be more verbose; can be repeated')

parser.add_argument('input', help='Input to pack')

def output_mrvc_file(args: argparse.Namespace) -> pathlib.Path:
  with open(args.input, 'rb') as in_file:
    code_contents = in_file.read()
    if not args.uncompressed:
      code_contents = compression.zstd.compress(code_contents, level=19)
    code_header = struct.pack('<cccI', b'\xAE', b'\x00', b'\x01', len(code_contents))

    code_blob = code_header + code_contents
    mrvc_path = pathlib.Path(args.input).with_suffix('.mrvc')
    code_hash = hashlib.new('keccak-256', code_blob).digest()
    print(f'{mrvc_path} => {code_hash.hex()}', file=sys.stdout)
    if not args.dry_run:
      with open(mrvc_path, 'wb') as out_file:
        out_file.write(code_blob)
  return mrvc_path

def main(args: argparse.Namespace) -> int:
  output_mrvc_file(args)
  return 0

if __name__ == '__main__':
  sys.exit(main(parser.parse_args()))
