// Copyright (C) 2025 Category Labs, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

#pragma once

// WARNING: THIS FILE CONTAINS GENERATED CODE, DO NOT EDIT MANUALLY! If
// you need changes, change the code generator or its inputs instead. This
// file was generated by running the following command:
//
//    util/ctypes/codegen/cg-ctypes -s category/vm/ctypes/v1 cxx-format -p
//    /home/ken/src/monad -fclang-format-19

/**
 * @file
 *
 * Defines std::formatter specializations for the C types in `evm_ctypes.h`
 */

#include <cstddef>
#include <format>
#include <iterator>
#include <span>
#include <string>
#include <utility>

#include <category/core/hex.hpp>
#include <category/vm/runtime/base_ctypes_fmt.hpp>
#include <category/vm/runtime/evm_ctypes.h>

template <>
struct std::formatter<monad_c_evm_intrinsic_gas> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto
    format(monad_c_evm_intrinsic_gas const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "evm_intrinsic_gas {{");
        i = std::format_to(i, "base = {}", value.base);
        i = std::format_to(i, ", data = {}", value.data);
        i = std::format_to(i, ", creation = {}", value.creation);
        i = std::format_to(i, ", access_list = {}", value.access_list);
        i = std::format_to(i, ", authorizations = {}", value.authorizations);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_c_evm_msg_call> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto format(monad_c_evm_msg_call const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "evm_msg_call {{");
        i = std::format_to(i, "opcode = {}", value.opcode);
        i = std::format_to(i, ", depth = {}", value.depth);
        i = std::format_to(i, ", gas = {}", value.gas);
        i = std::format_to(i, ", code_address = {}", value.code_address);
        i = std::format_to(i, ", sender = {}", value.sender);
        i = std::format_to(i, ", recipient = {}", value.recipient);
        i = std::format_to(i, ", value = {}", value.value);
        i = std::format_to(i, ", create2_salt = {}", value.create2_salt);
        i = std::format_to(
            i, ", input_data_length = {}", value.input_data_length);
        i = std::format_to(i, ", code_length = {}", value.code_length);
        *i++ = '}';
        auto const *p = reinterpret_cast<std::byte const *>(&value + 1);
        i = std::format_to(
            i,
            ", input_data = {:{#x}}",
            MONAD_NAMESPACE::as_hex(span{
                reinterpret_cast<std::byte const *>(p),
                static_cast<size_t>(value.input_data_length)}));
        p += value.input_data_length * sizeof(uint8_t);
        i = std::format_to(
            i,
            ", code = {:{#x}}",
            MONAD_NAMESPACE::as_hex(span{
                reinterpret_cast<std::byte const *>(p),
                static_cast<size_t>(value.code_length)}));
        p += value.code_length * sizeof(uint8_t);
        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_c_evm_result> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto format(monad_c_evm_result const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "evm_result {{");
        i = std::format_to(i, "status_code = {}", value.status_code);
        i = std::format_to(i, ", create_address = {}", value.create_address);
        i = std::format_to(i, ", gas_left = {}", value.gas_left);
        i = std::format_to(i, ", gas_refund = {}", value.gas_refund);
        i = std::format_to(
            i, ", output_data_length = {}", value.output_data_length);
        *i++ = '}';
        auto const *p = reinterpret_cast<std::byte const *>(&value + 1);
        i = std::format_to(
            i,
            ", output_data = {:{#x}}",
            MONAD_NAMESPACE::as_hex(span{
                reinterpret_cast<std::byte const *>(p),
                static_cast<size_t>(value.output_data_length)}));
        p += value.output_data_length * sizeof(uint8_t);
        return std::formatter<std::string>::format(s, ctx);
    }
};
