#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

enum monad_rv_exit_type
{
    MONAD_RV_EXIT_STOP,
    MONAD_RV_EXIT_RETURN,
    MONAD_RV_EXIT_REVERT,
};

enum monad_rv_syscall_domain : uint32_t
{
    MONAD_RV_SYSDOMAIN_EVM = 0,
    MONAD_RV_SYSDOMAIN_LIBC = 1,
    MONAD_RV_SYSDOMAIN_STDLIB = 2,
};

enum monad_rv_evm_syscall : uint64_t
{
    MONAD_RV_EVMSYS_CALL = (uint64_t)MONAD_RV_SYSDOMAIN_EVM << 32,
    MONAD_RV_EVMSYS_CALLDATA,
    MONAD_RV_EVMSYS_EXIT,
    MONAD_RV_EVMSYS_GAS,
    MONAD_RV_EVMSYS_KECCAK,
    MONAD_RV_EVMSYS_LOG,
    MONAD_RV_EVMSYS_MSG_SENDER,
    MONAD_RV_EVMSYS_RETURNDATA,
    MONAD_RV_EVMSYS_SLOAD,
    MONAD_RV_EVMSYS_SSTORE,
};

enum monad_rv_libc_syscall : uint64_t
{
    MONAD_RV_CSYS_ABORT = (uint64_t)MONAD_RV_SYSDOMAIN_LIBC << 32,
    MONAD_RV_CSYS_ALIGNED_ALLOC,
    MONAD_RV_CSYS_CALLOC,
    MONAD_RV_CSYS_FREE,
    MONAD_RV_CSYS_MALLOC,
    MONAD_RV_CSYS_MEMCHR,
    MONAD_RV_CSYS_MEMCMP,
    MONAD_RV_CSYS_MEMCPY,
    MONAD_RV_CSYS_MEMMOVE,
    MONAD_RV_CSYS_MEMSET,
    MONAD_RV_CSYS_REALLOC,
    MONAD_RV_CSYS_STPCPY,
    MONAD_RV_CSYS_STPNCPY,
    MONAD_RV_CSYS_STRCHR,
    MONAD_RV_CSYS_STRCPY,
    MONAD_RV_CSYS_STRERROR,
    MONAD_RV_CSYS_STRLCPY,
    MONAD_RV_CSYS_STRLEN,
    MONAD_RV_CSYS_STRNCPY,
    MONAD_RV_CSYS_STRRCHR,
    MONAD_RV_CSYS_VSNPRINTF,
    MONAD_RV_CSYS_VSPRINTF,
};

enum monad_rv_stdlib_syscall : uint64_t
{
    MONAD_RV_STDSYS_ASSERT_FAILED = (uint64_t)MONAD_RV_SYSDOMAIN_STDLIB << 32,
    MONAD_RV_STDSYS_UINT256_ADD,
    MONAD_RV_STDSYS_UINT256_LT,
    MONAD_RV_STDSYS_UINT256_SUB,
};

#ifdef __cplusplus
} // extern "C"
#endif
