// Copyright (C) 2025 Category Labs, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

#pragma once

// WARNING: THIS FILE CONTAINS GENERATED CODE, DO NOT EDIT MANUALLY! If
// you need changes, change the code generator or its inputs instead. This
// file was generated by running the following command:
//
//    util/ctypes/codegen/cg-ctypes -s category/execution/ctypes/v1
//    cxx-format -p /home/ken/src/monad -fclang-format-19

/**
 * @file
 *
 * Defines std::formatter specializations for the C types in
 * `exec_event_ctypes.h`
 */

#include <cstddef>
#include <format>
#include <iterator>
#include <span>
#include <string>
#include <utility>

#include <category/core/event/event_ring_fmt.hpp>
#include <category/core/hex.hpp>
#include <category/execution/ethereum/core/fmt/base_ctypes_fmt.hpp>
#include <category/execution/ethereum/core/fmt/eth_ctypes_fmt.hpp>
#include <category/execution/ethereum/event/exec_event_ctypes.h>
#include <category/execution/monad/core/fmt/monad_ctypes_fmt.hpp>

template <>
struct std::formatter<monad_exec_flow_type> : std::formatter<uint8_t>
{
    template <typename FormatContext>
    auto format(monad_exec_flow_type const &value, FormatContext &ctx) const
    {
        return std::formatter<uint8_t>::format(std::to_underlying(value), ctx);
    }
};

template <>
struct std::formatter<monad_exec_block_tag> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto format(monad_exec_block_tag const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "block_tag {{");
        i = std::format_to(i, "id = {}", value.id);
        i = std::format_to(i, ", block_number = {}", value.block_number);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_exec_block_start> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto format(monad_exec_block_start const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "block_start {{");
        i = std::format_to(i, "block_tag = {}", value.block_tag);
        i = std::format_to(i, ", round = {}", value.round);
        i = std::format_to(i, ", epoch = {}", value.epoch);
        i = std::format_to(
            i, ", proposal_epoch_nanos = {}", value.proposal_epoch_nanos);
        i = std::format_to(i, ", chain_id = {}", value.chain_id);
        i = std::format_to(i, ", author = {}", value.author);
        i = std::format_to(i, ", parent_eth_hash = {}", value.parent_eth_hash);
        i = std::format_to(i, ", eth_block_input = {}", value.eth_block_input);
        i = std::format_to(
            i, ", monad_block_input = {}", value.monad_block_input);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_exec_block_end> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto format(monad_exec_block_end const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "block_end {{");
        i = std::format_to(i, "eth_block_hash = {}", value.eth_block_hash);
        i = std::format_to(i, ", exec_output = {}", value.exec_output);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_exec_block_qc> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto format(monad_exec_block_qc const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "block_qc {{");
        i = std::format_to(i, "block_tag = {}", value.block_tag);
        i = std::format_to(i, ", round = {}", value.round);
        i = std::format_to(i, ", epoch = {}", value.epoch);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_exec_block_verified> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto
    format(monad_exec_block_verified const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "block_verified {{");
        i = std::format_to(i, "block_number = {}", value.block_number);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_exec_txn_header_start> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto
    format(monad_exec_txn_header_start const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "txn_header_start {{");
        i = std::format_to(i, "txn_hash = {}", value.txn_hash);
        i = std::format_to(i, ", sender = {}", value.sender);
        i = std::format_to(i, ", txn_header = {}", value.txn_header);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_exec_txn_access_list_entry>
    : std::formatter<std::string>
{
    template <typename FormatContext>
    auto format(
        monad_exec_txn_access_list_entry const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "txn_access_list_entry {{");
        i = std::format_to(i, "index = {}", value.index);
        i = std::format_to(i, ", entry = {}", value.entry);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_exec_txn_auth_list_entry>
    : std::formatter<std::string>
{
    template <typename FormatContext>
    auto format(
        monad_exec_txn_auth_list_entry const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "txn_auth_list_entry {{");
        i = std::format_to(i, "index = {}", value.index);
        i = std::format_to(i, ", entry = {}", value.entry);
        i = std::format_to(i, ", authority = {}", value.authority);
        i = std::format_to(
            i, ", is_valid_authority = {}", value.is_valid_authority);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_exec_txn_evm_output> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto
    format(monad_exec_txn_evm_output const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "txn_evm_output {{");
        i = std::format_to(i, "receipt = {}", value.receipt);
        i = std::format_to(
            i, ", call_frame_count = {}", value.call_frame_count);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_exec_txn_call_frame> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto
    format(monad_exec_txn_call_frame const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "txn_call_frame {{");
        i = std::format_to(i, "index = {}", value.index);
        i = std::format_to(i, ", caller = {}", value.caller);
        i = std::format_to(i, ", call_target = {}", value.call_target);
        i = std::format_to(i, ", opcode = {}", value.opcode);
        i = std::format_to(i, ", value = {}", value.value);
        i = std::format_to(i, ", gas = {}", value.gas);
        i = std::format_to(i, ", gas_used = {}", value.gas_used);
        i = std::format_to(i, ", evmc_status = {}", value.evmc_status);
        i = std::format_to(i, ", depth = {}", value.depth);
        i = std::format_to(i, ", input_length = {}", value.input_length);
        i = std::format_to(i, ", return_length = {}", value.return_length);
        *i++ = '}';
        auto const *p = reinterpret_cast<std::byte const *>(&value + 1);
        i = std::format_to(
            i,
            ", input = {:{#x}}",
            MONAD_NAMESPACE::as_hex(span{
                reinterpret_cast<std::byte const *>(p),
                static_cast<size_t>(value.input_length)}));
        p += value.input_length * sizeof(uint8_t);
        i = std::format_to(
            i,
            ", return = {:{#x}}",
            MONAD_NAMESPACE::as_hex(span{
                reinterpret_cast<std::byte const *>(p),
                static_cast<size_t>(value.return_length)}));
        p += value.return_length * sizeof(uint8_t);
        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_exec_account_access_context>
    : std::formatter<uint8_t>
{
    template <typename FormatContext>
    auto format(
        monad_exec_account_access_context const &value,
        FormatContext &ctx) const
    {
        return std::formatter<uint8_t>::format(std::to_underlying(value), ctx);
    }
};

template <>
struct std::formatter<monad_exec_account_access_list_header>
    : std::formatter<std::string>
{
    template <typename FormatContext>
    auto format(
        monad_exec_account_access_list_header const &value,
        FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "account_access_list_header {{");
        i = std::format_to(i, "entry_count = {}", value.entry_count);
        i = std::format_to(i, ", access_context = {}", value.access_context);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_exec_account_access> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto
    format(monad_exec_account_access const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "account_access {{");
        i = std::format_to(i, "index = {}", value.index);
        i = std::format_to(i, ", address = {}", value.address);
        i = std::format_to(i, ", access_context = {}", value.access_context);
        i = std::format_to(
            i, ", is_balance_modified = {}", value.is_balance_modified);
        i = std::format_to(
            i, ", is_nonce_modified = {}", value.is_nonce_modified);
        i = std::format_to(i, ", prestate = {}", value.prestate);
        i = std::format_to(
            i, ", modified_balance = {}", value.modified_balance);
        i = std::format_to(i, ", modified_nonce = {}", value.modified_nonce);
        i = std::format_to(
            i, ", storage_key_count = {}", value.storage_key_count);
        i = std::format_to(i, ", transient_count = {}", value.transient_count);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_exec_storage_access> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto
    format(monad_exec_storage_access const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "storage_access {{");
        i = std::format_to(i, "address = {}", value.address);
        i = std::format_to(i, ", index = {}", value.index);
        i = std::format_to(i, ", access_context = {}", value.access_context);
        i = std::format_to(i, ", modified = {}", value.modified);
        i = std::format_to(i, ", transient = {}", value.transient);
        i = std::format_to(i, ", key = {}", value.key);
        i = std::format_to(i, ", start_value = {}", value.start_value);
        i = std::format_to(i, ", end_value = {}", value.end_value);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

template <>
struct std::formatter<monad_exec_evm_error> : std::formatter<std::string>
{
    template <typename FormatContext>
    auto format(monad_exec_evm_error const &value, FormatContext &ctx) const
    {
        using MONAD_NAMESPACE::as_hex;
        std::string s;
        std::back_insert_iterator i{s};
        i = std::format_to(i, "evm_error {{");
        i = std::format_to(i, "domain_id = {}", value.domain_id);
        i = std::format_to(i, ", status_code = {}", value.status_code);
        *i++ = '}';

        return std::formatter<std::string>::format(s, ctx);
    }
};

namespace category_labs
{

    template <std::output_iterator<char> Out>
    Out
    format_as(Out o, void const *payload_buf, monad_exec_event_type event_type)
    {
        switch (event_type) {
        case MONAD_EXEC_NONE:
            return o;
        case MONAD_EXEC_RECORD_ERROR:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_record_error const *>(payload_buf));
        case MONAD_EXEC_BLOCK_START:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_block_start const *>(payload_buf));
        case MONAD_EXEC_BLOCK_REJECT:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_block_reject const *>(payload_buf));
        case MONAD_EXEC_BLOCK_PERF_EVM_ENTER:
            return o;
        case MONAD_EXEC_BLOCK_PERF_EVM_EXIT:
            return o;
        case MONAD_EXEC_BLOCK_END:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_block_end const *>(payload_buf));
        case MONAD_EXEC_BLOCK_QC:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_block_qc const *>(payload_buf));
        case MONAD_EXEC_BLOCK_FINALIZED:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_block_finalized const *>(payload_buf));
        case MONAD_EXEC_BLOCK_VERIFIED:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_block_verified const *>(payload_buf));
        case MONAD_EXEC_TXN_HEADER_START:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_txn_header_start const *>(payload_buf));
        case MONAD_EXEC_TXN_ACCESS_LIST_ENTRY:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_txn_access_list_entry const *>(
                    payload_buf));
        case MONAD_EXEC_TXN_AUTH_LIST_ENTRY:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_txn_auth_list_entry const *>(
                    payload_buf));
        case MONAD_EXEC_TXN_HEADER_END:
            return o;
        case MONAD_EXEC_TXN_REJECT:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_txn_reject const *>(payload_buf));
        case MONAD_EXEC_TXN_PERF_EVM_ENTER:
            return o;
        case MONAD_EXEC_TXN_PERF_EVM_EXIT:
            return o;
        case MONAD_EXEC_TXN_EVM_OUTPUT:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_txn_evm_output const *>(payload_buf));
        case MONAD_EXEC_TXN_LOG:
            return std::format_to(
                o, "{}", *static_cast<monad_exec_txn_log const *>(payload_buf));
        case MONAD_EXEC_TXN_CALL_FRAME:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_txn_call_frame const *>(payload_buf));
        case MONAD_EXEC_TXN_END:
            return o;
        case MONAD_EXEC_ACCOUNT_ACCESS_LIST_HEADER:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_account_access_list_header const *>(
                    payload_buf));
        case MONAD_EXEC_ACCOUNT_ACCESS:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_account_access const *>(payload_buf));
        case MONAD_EXEC_STORAGE_ACCESS:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_storage_access const *>(payload_buf));
        case MONAD_EXEC_EVM_ERROR:
            return std::format_to(
                o,
                "{}",
                *static_cast<monad_exec_evm_error const *>(payload_buf));
        default:
            return std::format_to(
                o, "unknown exec type code {}", std::to_underlying(event_type));
        }
        std::unreachable();
    }

} // namespace category_labs
