// Copyright (C) 2025 Category Labs, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// WARNING: THIS FILE CONTAINS GENERATED CODE, DO NOT EDIT MANUALLY! If
// you need changes, change the code generator or its inputs instead. This
// file was generated by running the following command:
//
//    util/ctypes/codegen/cg-ctypes -s category/vm/ctypes/v1 c -p
//    /home/ken/src/monad-wt1 -fclang-format-19

#include <stdint.h>

#include <category/core/event/event_metadata.h>
#include <category/vm/event/evmt_event_ctypes.h>

#ifdef __cplusplus
extern "C"
{
#endif

struct monad_event_metadata const
    g_monad_evmt_event_metadata[MONAD_EVMT_EVENT_COUNT] = {

        [MONAD_EVMT_NONE] =
            {.event_type = MONAD_EVMT_NONE,
             .c_name = "NONE",
             .description = "Reserved code so that 0 remains invalid"},

        [MONAD_EVMT_RECORD_ERROR] =
            {.event_type = MONAD_EVMT_RECORD_ERROR,
             .c_name = "RECORD_ERROR",
             .description = "Reserved event type used for recording errors"},

        [MONAD_EVMT_TXN_START] =
            {.event_type = MONAD_EVMT_TXN_START,
             .c_name = "TXN_START",
             .description = "Marker event recorded at the start of transaction "
                            "processing"},

        [MONAD_EVMT_TXN_REJECT] =
            {.event_type = MONAD_EVMT_TXN_REJECT,
             .c_name = "TXN_REJECT",
             .description = "Event recorded when a transaction is rejected "
                            "(i.e., is invalid)"},

        [MONAD_EVMT_TXN_EVM_ENTER] =
            {.event_type = MONAD_EVMT_TXN_EVM_ENTER,
             .c_name = "TXN_EVM_ENTER",
             .description =
                 "Event recorded after validation of transaction is complete"},

        [MONAD_EVMT_TXN_EVM_EXIT] =
            {.event_type = MONAD_EVMT_TXN_EVM_EXIT,
             .c_name = "TXN_EVM_EXIT",
             .description =
                 "Event recorded immediatey after EVM execution is complete"},

        [MONAD_EVMT_MSG_CALL_ENTER] =
            {.event_type = MONAD_EVMT_MSG_CALL_ENTER,
             .c_name = "MSG_CALL_ENTER",
             .description =
                 "Event recorded to introduce the scope of a message call"},

        [MONAD_EVMT_MSG_CALL_EXIT] =
            {.event_type = MONAD_EVMT_MSG_CALL_EXIT,
             .c_name = "MSG_CALL_EXIT",
             .description =
                 "Event recorded to exit the scope of a message call"},

        [MONAD_EVMT_TXN_STALL] =
            {.event_type = MONAD_EVMT_TXN_STALL,
             .c_name = "TXN_STALL",
             .description = "Event recorded before a transaction fiber sleeps "
                            "on the merge synchronization primitive"},

        [MONAD_EVMT_TXN_RESTART] =
            {.event_type = MONAD_EVMT_TXN_RESTART,
             .c_name = "TXN_RESTART",
             .description = "Marker event recorded when a transaction must "
                            "re-execute because of a merge conflict"},

        [MONAD_EVMT_TXN_END] =
            {.event_type = MONAD_EVMT_TXN_END,
             .c_name = "TXN_END",
             .description =
                 "Event recorded when transaction processing finished"},

        [MONAD_EVMT_EVM_ERROR] =
            {.event_type = MONAD_EVMT_EVM_ERROR,
             .c_name = "EVM_ERROR",
             .description = "Error occurred in execution process (not a "
                            "validation error)"},

        [MONAD_EVMT_VM_DECODE] =
            {.event_type = MONAD_EVMT_VM_DECODE,
             .c_name = "VM_DECODE",
             .description =
                 "Event emitted when an EVM instruction is executed"},
};

uint8_t const g_monad_evmt_event_schema_hash[32] = {
    0x33, 0x34, 0xa2, 0xda, 0xe1, 0x19, 0x99, 0xb4, 0x8d, 0x1f, 0x61,
    0xcd, 0x15, 0x51, 0x31, 0xa3, 0x41, 0xbc, 0x71, 0xb0, 0xcd, 0xda,
    0x82, 0x50, 0x4a, 0xd1, 0xa8, 0x03, 0xa5, 0x52, 0x1a, 0x04,
};

#ifdef __cplusplus
} // extern "C"
#endif
