// Copyright (C) 2025 Category Labs, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// WARNING: THIS FILE CONTAINS GENERATED CODE, DO NOT EDIT MANUALLY! If
// you need changes, change the code generator or its inputs instead. This
// file was generated by running the following command:
//
//    util/ctypes/codegen/cg-ctypes -s category/vm/ctypes/v1 c -p
//    /home/ken/src/monad-wt1 -fclang-format-19

#include <stdint.h>

#include <category/core/event/event_metadata.h>
#include <category/vm/event/evmt_event_ctypes.h>

#ifdef __cplusplus
extern "C"
{
#endif

struct monad_event_metadata const
    g_monad_evmt_event_metadata[MONAD_EVMT_EVENT_COUNT] = {

        [MONAD_EVMT_NONE] =
            {.event_type = MONAD_EVMT_NONE,
             .c_name = "NONE",
             .description = "Reserved code so that 0 remains invalid"},

        [MONAD_EVMT_RECORD_ERROR] =
            {.event_type = MONAD_EVMT_RECORD_ERROR,
             .c_name = "RECORD_ERROR",
             .description = "Reserved event type used for recording errors"},

        [MONAD_EVMT_TXN_START] =
            {.event_type = MONAD_EVMT_TXN_START,
             .c_name = "TXN_START",
             .description = "Marker event recorded at the start of transaction "
                            "processing"},

        [MONAD_EVMT_TXN_REJECT] =
            {.event_type = MONAD_EVMT_TXN_REJECT,
             .c_name = "TXN_REJECT",
             .description = "Event recorded when a transaction is rejected "
                            "(i.e., is invalid)"},

        [MONAD_EVMT_TXN_EVM_ENTER] =
            {.event_type = MONAD_EVMT_TXN_EVM_ENTER,
             .c_name = "TXN_EVM_ENTER",
             .description =
                 "Event recorded after validation of transaction is complete"},

        [MONAD_EVMT_TXN_EVM_EXIT] =
            {.event_type = MONAD_EVMT_TXN_EVM_EXIT,
             .c_name = "TXN_EVM_EXIT",
             .description =
                 "Event recorded immediatey after EVM execution is complete"},

        [MONAD_EVMT_TXN_STALL] =
            {.event_type = MONAD_EVMT_TXN_STALL,
             .c_name = "TXN_STALL",
             .description = "Event recorded before a transaction fiber sleeps "
                            "on the merge synchronization primitive"},

        [MONAD_EVMT_TXN_RESTART] =
            {.event_type = MONAD_EVMT_TXN_RESTART,
             .c_name = "TXN_RESTART",
             .description = "Marker event recorded when a transaction must "
                            "re-execute because of a merge conflict"},

        [MONAD_EVMT_TXN_END] =
            {.event_type = MONAD_EVMT_TXN_END,
             .c_name = "TXN_END",
             .description =
                 "Event recorded when transaction processing finished"},

        [MONAD_EVMT_EVM_ERROR] =
            {.event_type = MONAD_EVMT_EVM_ERROR,
             .c_name = "EVM_ERROR",
             .description = "Error occurred in execution process (not a "
                            "validation error)"},
};

uint8_t const g_monad_evmt_event_schema_hash[32] = {
    0x48, 0x4b, 0x64, 0x0e, 0xb5, 0xb9, 0xe5, 0xbc, 0x53, 0x21, 0x82,
    0xdb, 0x24, 0x15, 0xfa, 0x3c, 0x8b, 0x96, 0x72, 0xbc, 0xcf, 0x5c,
    0xb3, 0xb7, 0x70, 0x64, 0xac, 0xdf, 0xa9, 0x77, 0x33, 0xf7,
};

#ifdef __cplusplus
} // extern "C"
#endif
