// Copyright (C) 2025 Category Labs, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// WARNING: THIS FILE CONTAINS GENERATED CODE, DO NOT EDIT MANUALLY! If
// you need changes, change the code generator or its inputs instead. This
// file was generated by running the following command:
//
//    util/ctypes/codegen/cg-ctypes -s category/vm/ctypes/v1 c
//    -fclang-format-19 -p /home/ken/src/monad

#include <stdint.h>

#include <category/core/event/event_metadata.h>
#include <category/vm/event/evmt_event_ctypes.h>

#ifdef __cplusplus
extern "C"
{
#endif

struct monad_event_metadata const
    g_monad_evmt_event_metadata[MONAD_EVMT_EVENT_COUNT] = {

        [MONAD_EVMT_NONE] =
            {.event_type = MONAD_EVMT_NONE,
             .c_name = "NONE",
             .description = "Reserved code so that 0 remains invalid"},

        [MONAD_EVMT_RECORD_ERROR] =
            {.event_type = MONAD_EVMT_RECORD_ERROR,
             .c_name = "RECORD_ERROR",
             .description = "Reserved event type used for recording errors"},

        [MONAD_EVMT_TXN_START] =
            {.event_type = MONAD_EVMT_TXN_START,
             .c_name = "TXN_START",
             .description = "Marker event recorded at the start of transaction "
                            "processing"},

        [MONAD_EVMT_TXN_REJECT] =
            {.event_type = MONAD_EVMT_TXN_REJECT,
             .c_name = "TXN_REJECT",
             .description = "Event recorded when a transaction is rejected "
                            "(i.e., is invalid)"},

        [MONAD_EVMT_TXN_STALL] =
            {.event_type = MONAD_EVMT_TXN_STALL,
             .c_name = "TXN_STALL",
             .description = "Event recorded before a transaction fiber sleeps "
                            "on the merge synchronization primitive"},

        [MONAD_EVMT_TXN_RESTART] =
            {.event_type = MONAD_EVMT_TXN_RESTART,
             .c_name = "TXN_RESTART",
             .description = "Marker event recorded when a transaction must "
                            "re-execute because of a merge conflict"},

        [MONAD_EVMT_TXN_END] =
            {.event_type = MONAD_EVMT_TXN_END,
             .c_name = "TXN_END",
             .description =
                 "Event recorded when transaction processing finished"},

        [MONAD_EVMT_EVM_ERROR] =
            {.event_type = MONAD_EVMT_EVM_ERROR,
             .c_name = "EVM_ERROR",
             .description = "Error occurred in execution process (not a "
                            "validation error)"},
};

uint8_t const g_monad_evmt_event_schema_hash[32] = {
    0xbc, 0x79, 0x75, 0xf8, 0xbe, 0xd8, 0xf8, 0xf9, 0x85, 0xfe, 0xdd,
    0x5f, 0x39, 0xdb, 0xee, 0xf5, 0xa8, 0x9e, 0xc6, 0x32, 0xd4, 0xb2,
    0x5d, 0x21, 0x82, 0xe9, 0xf6, 0x41, 0x1e, 0x65, 0xd5, 0xd5,
};

#ifdef __cplusplus
} // extern "C"
#endif
